### ISSUE TITLE
Code Issue

### ISSUE THREAD

**Issue by MustafaRazaUllah** [umaraslam-cs/stripe_flutter#1]
**Code not a work on iOS and Android**

<img width="1121" alt="Screenshot 2023-03-08 at 5 21 22 PM" src="https://user-images.githubusercontent.com/104248211/223712048-e33e061e-d8d5-4866-811a-3e135c5a6bb6.png">

<img width="1125" alt="Screenshot 2023-03-08 at 5 22 29 PM" src="https://user-images.githubusercontent.com/104248211/223712286-eb3d6504-92cb-499e-ac85-e7f0efd9407a.png">

**Flutter version is** 

Flutter 3.7.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 12cb4eb7a0 (7 days ago) • 2023-03-01 10:29:26 -0800
Engine • revision ada363ee93
Tools • Dart 2.19.3 • DevTools 2.20.1

**Comment by Numanshakir** [comment]
@MustafaRazaUllah 
I think you have to create .env file which contains the Stripe Secret key 
@umaraslam-cs  
can you please provide the file with test or empty key

**Comment by MustafaRazaUllah** [comment]
please write down .env file format @Numanshakir  thank you

**Comment by Numanshakir** [comment]
@MustafaRazaUllah 
https://pub.dev/packages/flutter_dotenv

visit this plugin

**Comment by umaraslam-cs** [comment]
Thanks for helping @Numanshakir
